/* Generated by wayland-scanner 1.23.1 */

#ifndef AETHER_IPC_V1_CLIENT_PROTOCOL_H
#define AETHER_IPC_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_aether_ipc_v1 The aether_ipc_v1 protocol
 * @section page_ifaces_aether_ipc_v1 Interfaces
 * - @subpage page_iface_aether_ipc_manager_v1 - Aether compositor IPC manager
 * @section page_copyright_aether_ipc_v1 Copyright
 * <pre>
 *
 * Copyright (C) 2024 Aether Compositor Authors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct aether_ipc_manager_v1;

#ifndef AETHER_IPC_MANAGER_V1_INTERFACE
#define AETHER_IPC_MANAGER_V1_INTERFACE
/**
 * @page page_iface_aether_ipc_manager_v1 aether_ipc_manager_v1
 * @section page_iface_aether_ipc_manager_v1_desc Description
 *
 * This global interface is the entry point for all IPC communication with
 * the Aether Wayland compositor.  Clients bind it via wl_registry and
 * immediately start receiving workspace and keyboard state events.
 *
 * The compositor sends the initial state as soon as the bind completes so
 * clients can initialise without an explicit query.
 * @section page_iface_aether_ipc_manager_v1_api API
 * See @ref iface_aether_ipc_manager_v1.
 */
/**
 * @defgroup iface_aether_ipc_manager_v1 The aether_ipc_manager_v1 interface
 *
 * This global interface is the entry point for all IPC communication with
 * the Aether Wayland compositor.  Clients bind it via wl_registry and
 * immediately start receiving workspace and keyboard state events.
 *
 * The compositor sends the initial state as soon as the bind completes so
 * clients can initialise without an explicit query.
 */
extern const struct wl_interface aether_ipc_manager_v1_interface;
#endif

/**
 * @ingroup iface_aether_ipc_manager_v1
 * @struct aether_ipc_manager_v1_listener
 */
struct aether_ipc_manager_v1_listener {
	/**
	 * workspace state for one output
	 *
	 * Sent whenever the active workspace on any output changes, and
	 * once immediately after the client binds the interface.
	 *
	 * grid_width × grid_height gives the total number of workspaces.
	 * x and y are the coordinates of the currently active workspace
	 * (zero-based, within the grid).
	 * @param output_id output index
	 * @param x active workspace column
	 * @param y active workspace row
	 * @param grid_width number of workspace columns
	 * @param grid_height number of workspace rows
	 */
	void (*workspace_state)(void *data,
				struct aether_ipc_manager_v1 *aether_ipc_manager_v1,
				int32_t output_id,
				int32_t x,
				int32_t y,
				int32_t grid_width,
				int32_t grid_height);
	/**
	 * keyboard layout state
	 *
	 * Sent whenever the active keyboard layout changes, and once
	 * immediately after the client binds the interface.
	 *
	 * layouts is a newline-separated list of layout names (e.g.
	 * "English\nArabic"). layout_index is the zero-based index of the
	 * currently active layout within that list.
	 * @param layouts newline-separated layout names
	 * @param layout_index index of the active layout
	 */
	void (*keyboard_state)(void *data,
			       struct aether_ipc_manager_v1 *aether_ipc_manager_v1,
			       const char *layouts,
			       int32_t layout_index);
};

/**
 * @ingroup iface_aether_ipc_manager_v1
 */
static inline int
aether_ipc_manager_v1_add_listener(struct aether_ipc_manager_v1 *aether_ipc_manager_v1,
				   const struct aether_ipc_manager_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) aether_ipc_manager_v1,
				     (void (**)(void)) listener, data);
}

#define AETHER_IPC_MANAGER_V1_DESTROY 0
#define AETHER_IPC_MANAGER_V1_SET_WORKSPACE 1

/**
 * @ingroup iface_aether_ipc_manager_v1
 */
#define AETHER_IPC_MANAGER_V1_WORKSPACE_STATE_SINCE_VERSION 1
/**
 * @ingroup iface_aether_ipc_manager_v1
 */
#define AETHER_IPC_MANAGER_V1_KEYBOARD_STATE_SINCE_VERSION 1

/**
 * @ingroup iface_aether_ipc_manager_v1
 */
#define AETHER_IPC_MANAGER_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_aether_ipc_manager_v1
 */
#define AETHER_IPC_MANAGER_V1_SET_WORKSPACE_SINCE_VERSION 1

/** @ingroup iface_aether_ipc_manager_v1 */
static inline void
aether_ipc_manager_v1_set_user_data(struct aether_ipc_manager_v1 *aether_ipc_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) aether_ipc_manager_v1, user_data);
}

/** @ingroup iface_aether_ipc_manager_v1 */
static inline void *
aether_ipc_manager_v1_get_user_data(struct aether_ipc_manager_v1 *aether_ipc_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) aether_ipc_manager_v1);
}

static inline uint32_t
aether_ipc_manager_v1_get_version(struct aether_ipc_manager_v1 *aether_ipc_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) aether_ipc_manager_v1);
}

/**
 * @ingroup iface_aether_ipc_manager_v1
 *
 * Destroys the aether_ipc_manager_v1 object.  The compositor will stop
 * sending events to this client.
 */
static inline void
aether_ipc_manager_v1_destroy(struct aether_ipc_manager_v1 *aether_ipc_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) aether_ipc_manager_v1,
			 AETHER_IPC_MANAGER_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) aether_ipc_manager_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_aether_ipc_manager_v1
 *
 * Request that the compositor change the active workspace on the output
 * identified by output_id to the workspace at grid position (x, y).
 *
 * Grid coordinates are zero-based.  The compositor will reply with a
 * workspace_state event reflecting the new state.
 */
static inline void
aether_ipc_manager_v1_set_workspace(struct aether_ipc_manager_v1 *aether_ipc_manager_v1, int32_t output_id, int32_t x, int32_t y)
{
	wl_proxy_marshal_flags((struct wl_proxy *) aether_ipc_manager_v1,
			 AETHER_IPC_MANAGER_V1_SET_WORKSPACE, NULL, wl_proxy_get_version((struct wl_proxy *) aether_ipc_manager_v1), 0, output_id, x, y);
}

#ifdef  __cplusplus
}
#endif

#endif
